### PR TITLE
Remove pin/unpin handling from AboutNewTab.jsm.

### PR DESCRIPTION
**Pull request by emtwo**
This patch goes along with the remote-newtab pull request: https://github.com/mozilla/remote-newtab/pull/74

r? @oyiptong or @marcoscaceres or @sarracini

### CODE REVIEW

**Comment by emtwo** [comment]
@marcoscaceres Forgot to wrap this one up with the remote-newtab pinned links stuff. r?

**Comment by marcoscaceres** [comment]
@emtwo see: 
https://github.com/mozilla/newtab-dev/pull/18#issuecomment-143914868

Should be a similar process here. Let me know how you want to proceed.

**Comment by emtwo** [comment]
@marcoscaceres rebase is complete. r?

**Comment by oyiptong** [comment]
r+

**Pull request merged**
