### PR TITLE
Ensure data coming from the page is always a string

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@oyiptong, right now, the security violations are just silently swallowed by the program and re-routed to the error console. This makes it difficult to observe, and also to test, the violations (by design). I don't think we want to make it start throwing exceptions (because it's a message listener, hence there is nothing that can catch those exceptions in a useful way) or sending error messages back to the page. 

So, not sure exactly what we want to test here, apart from the "right" behavior - which is currently what we test for. I.e., only legitimate messages get through... everything else would just time out and do nothing. Not sure how to test for that tho?

**Comment by oyiptong** [comment]
We want to test the right behavior. That's pretty much it.

It gives us a safeguard in case something else breaks.

**Comment by oyiptong** [comment]
Actually, the messaging may already be tested elsewhere, so tests in this branch may not be necessary.

When we test for say pins being sent to the privileged context, it will make use of this codepath

**Comment by sarracini** [comment]
r+

**Comment by marcoscaceres** [comment]
@oyiptong this one went missing?

**Comment by oyiptong** [comment]
Yes. It's my failt

**Comment by oyiptong** [comment]
Fault

**Comment by marcoscaceres** [comment]
If it was not you, it would have been me! :D

**Comment by oyiptong** [comment]
Let's get @emtwo to review then we land

**Comment by oyiptong** [comment]
We need to wait on @Mardak's review to land everything though

**Pull request merged**
