### PR TITLE
Bug 1212897 - Pass strings instead of objects from remote page to content process

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
This change got lost somewhere along the way...

**Comment by marcoscaceres** [comment]
@oyiptong r?

**Comment by oyiptong** [comment]
R+

**Comment by marcoscaceres** [comment]
@oyiptong I cherry-picked the security check that went missing back into this one.

**Comment by marcoscaceres** [comment]
@oyiptong hmm, just realized that this is currently going to be missing from gecko. Can we should merge this and recreate the patch, I guess.

**Comment by marcoscaceres** [comment]
Added comments that @mikeconley requested.

**Comment by oyiptong** [comment]
Hmm I added comments as well

**Comment by oyiptong** [comment]
Did you rebase onto the latest master?

**Comment by marcoscaceres** [comment]
Yep, latest.

**Comment by oyiptong** [comment]
new comments that @mikeconley requested: https://github.com/mozilla/newtab-dev/commit/040570339d3aea0a06d45b31c0b954ccabb2a870

**Comment by oyiptong** [comment]
ah yes, i was on my mobile, didn't see the head this was based on. never mind

me_dancing

**Comment by oyiptong** [comment]
Please modify tests in https://github.com/mozilla/newtab-dev/blob/4d35139ff90355d73077ab2b252efc55c3ebc300/browser/components/newtab/tests/browser/browser_remotenewtab_pageloads.js

**Pull request closed without merging**
