### PR TITLE
Ensure data coming from the page is always a string

### PR DESCRIPTION
**Pull request by marcoscaceres**
Must merge with https://github.com/mozilla/remote-newtab/pull/90

### CODE REVIEW

**Comment by marcoscaceres** [comment]
R?

**Comment by emtwo** [comment]
r+

**Comment by marcoscaceres** [comment]
Would like to use the test infra from #14, but need that one to land first.

**Comment by marcoscaceres** [comment]
Resending as merge conflicts and massive rebase needed.

**Pull request closed without merging**
